import json

def biliup_to_string(biliup_cookie_path: str = 'cookies.json') -> str:
    try:
        r = ''
        biliup_json_obj = json.load(open(biliup_cookie_path))
        for cookie in biliup_json_obj['cookie_info']['cookies']:
            r += f'{cookie["name"]}={cookie["value"]}; '
        return r
    except Exception:
        return ""

def biliup_to_ytbdl_cookie(biliup_json_obj: dict) -> list:
    r = []
    for cookie in biliup_json_obj['cookie_info']['cookies']:
        r.append([
            '.bilibili.com',
            'TRUE',
            '/',
            'TRUE' if cookie['secure'] == 1 else "FALSE",
            str(cookie['expires']),
            str(cookie['name']),
            str(cookie['value']),
        ])
    return r

def biliup_to_ytbdl_cookie_write2file(
    biliup_cookie_path: str = 'cookies.json',
    ytbdl_cookie_path:  str = 'ytdlp_cookies.txt') -> None:
    with open(biliup_cookie_path) as f:
        r = [ '\t'.join(i) for i in biliup_to_ytbdl_cookie(json.load(f))]
    with open(ytbdl_cookie_path, 'w') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# This file is generated by biliup-\
        cookie-ytdlp converter.  Do not edit.\n')
        f.write('\n')
        for line in r:
            f.write(line + '\n')

if __name__ == "__main__":
    biliup_to_ytbdl_cookie_write2file()